services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.local.wwwfake.com`)"
      - "traefik.http.routers.jackett.entrypoints=https"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    networks:
      - proxy
    container_name: jackett
    environment:
      - PUID=1000  # Adjust according to your user ID
      - PGID=1000  # Adjust according to your group ID
      - TZ=America/Denver  # Adjust according to your timezone
    volumes:
      - arr_jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.wwwfake.com`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy
    environment:
      - PUID=1000  # Adjust according to your user ID
      - PGID=1000  # Adjust according to your group ID
      - TZ=America/Denver  # Adjust according to your timezone
    volumes:
      - arr_radarr:/config
      - /mnt/media/Movies:/mnt/movies
      - /mnt/media/downloads:/mnt/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.local.wwwfake.com`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    networks:
      - proxy
    environment:
      - PUID=1000  # Adjust according to your user ID
      - PGID=1000  # Adjust according to your group ID
      - TZ=America/Denver  # Set timezone to Denver
      - WEBUI_PORT=8080  # Port for qBittorrent Web UI
    volumes:
      - arr_qbittorrent:/config
      - /mnt/media/downloads:/mnt/downloads
      - /mnt/media/Movies:/mnt/movies
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Limit to 2 CPU
    container_name: sabnzbd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.local.wwwfake.com`)"
      - "traefik.http.routers.sabnzbd.entrypoints=https"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8081"
    networks:
      - proxy
    environment:
      - PUID=1000  # Adjust according to your user ID
      - PGID=1000  # Adjust according to your group ID
      - TZ=America/Denver  # Set timezone to Denver
    volumes:
      - arr_sabnzbd:/config
      - /mnt/media/downloads:/mnt/downloads
      - /mnt/media/Movies:/mnt/movies
    ports:
      - 8081:8081
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local.wwwfake.com`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy
    environment:
      - PUID=1000  # Adjust according to your user ID
      - PGID=1000  # Adjust according to your group ID
      - TZ=America/Denver  # Set timezone to Denver
    volumes:
      - arr_sonarr:/config
      - /mnt/media/Shows:/mnt/shows
      - /mnt/media/downloads:/mnt/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.local.wwwfake.com`)"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - proxy
    environment:
      - LOG_LEVEL=info
      - TZ=America/Denver  # Set timezone to Denver
      - PUID=1001  # Adjust according to your user ID
      - PGID=1001  # Adjust according to your group ID
    volumes:
      - arr_overseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  arr_jackett:
    external: true
  arr_radarr:
    external: true
  arr_qbittorrent:
    external: true
  arr_sabnzbd:
    external: true
  arr_sonarr:
    external: true
  arr_overseerr:
    external: true

networks:
  proxy:
    external: true
